"""
05_common_real_test_utility.py
==============================

HFAGM revision - common untouched real-test downstream utility audit.

REVIEWER PURPOSE
----------------
Reviewer #3 requested that downstream utility be evaluated using a common,
untouched real test set. Historical figures compared conditions using different
numbers of observations, so those comparisons cannot establish controlled
utility differences.

THIS SCRIPT
-----------
1. Loads the original 193-record COVID clinical dataset.
2. Reconstructs the verified 51-feature schema.
3. Creates ONE locked stratified real-data split.
4. Fits all preprocessing ONLY on the locked real training partition.
5. Trains the same preserved classifier architecture on real training data.
6. Evaluates it on the locked untouched real test set.
7. Audits the project for existing labeled 51-feature synthetic datasets.
8. Permits a synthetic-training utility experiment ONLY when provenance proves:
       a. the synthetic table has all 51 predictors;
       b. it has the same binary target;
       c. it was generated exclusively from the locked real training rows;
       d. its provenance identifies the same locked split;
       e. no test rows contributed to synthetic generation.
9. If such provenance is absent, reports synthetic utility as NOT_RECOMPUTABLE.
10. Never generates synthetic data.

PRIMARY PRINCIPLE
-----------------
Every downstream utility condition must be evaluated on:

    THE SAME LOCKED UNTOUCHED REAL TEST SET

The classifier architecture and evaluation implementation must also be the same.

PRIMARY REAL CONDITION
----------------------
real_training_unbalanced

This matches the corrected 02E conclusion that the ordinary unbalanced real
training condition was the simpler primary reference.

OPTIONAL SYNTHETIC CONDITION
----------------------------
synthetic_training_verified

Only activated if an existing synthetic training table passes all provenance
requirements.

NO synthetic table is generated by this script.

OUTPUT
------
outputs/revision_utility/common_real_test/

    locked_split_manifest.csv
    locked_train_indices.csv
    locked_test_indices.csv
    locked_test_data.csv
    real_training_data_audit.csv
    preprocessing_audit.csv
    common_test_integrity_audit.csv
    classifier_provenance.csv

    synthetic_candidate_inventory.csv
    synthetic_provenance_audit.csv
    admissible_synthetic_training_sets.csv

    utility_predictions.csv
    utility_confusion_matrices.csv
    utility_metrics.csv
    utility_comparison.csv
    utility_verdict.csv
    utility_provenance.csv
    common_real_test_utility_summary.txt

IMPORTANT
---------
A missing synthetic utility result is scientifically preferable to an invalid
comparison.

If no training-only synthetic dataset exists, the valid conclusion is:

    SYNTHETIC_UTILITY_NOT_RECOMPUTABLE_FROM_RECOVERED_ARTIFACTS

That result should be used to remove unsupported historical real-vs-synthetic
utility claims rather than silently replacing them with a new experiment.
"""

from __future__ import annotations

import hashlib
import json
import math
import sys
import traceback

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import joblib
import numpy as np
import pandas as pd
import scipy
import sklearn

from sklearn.base import clone
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler


# =============================================================================
# 1. CONFIGURATION
# =============================================================================

PROJECT_ROOT = Path(
    r"D:\47\472\New-Papers\Array\Paper4-Under-Processing\HFAGM_Project"
)

RAW_CSV_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "covid_clinical.csv"
)

RAW_XLSX_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "covid_clinical.xlsx"
)

FEATURE_SCHEMA_PATH = (
    PROJECT_ROOT
    / "data"
    / "preprocessed"
    / "X_train_scaled.csv"
)

PRESERVED_CLASSIFIER_PATH = (
    PROJECT_ROOT
    / "models"
    / "classifiers"
    / "ensemble_model.pkl"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "revision_utility"
    / "common_real_test"
)

EXPECTED_REAL_ROWS = 193
EXPECTED_FEATURE_COUNT = 51

LOCKED_SPLIT_SEED = 42
LOCKED_TEST_SIZE = 0.20

TARGET_CANDIDATES = [
    "status",
    "Status",
    "STATUS",
    "target",
    "Target",
    "label",
    "Label",
    "outcome",
    "Outcome",
]

TABULAR_EXTENSIONS = {
    ".csv",
    ".tsv",
    ".xlsx",
    ".xls",
    ".parquet",
}

SYNTHETIC_HINTS = (
    "synthetic",
    "generated",
    "fake",
    "synth",
)

EXCLUDED_DIR_EXACT = {
    ".git",
    "__pycache__",
    "site-packages",
    "dist-packages",
    "node_modules",
    ".pytest_cache",
    ".idea",
    ".vscode",
}

EXCLUDED_DIR_PREFIXES = (
    ".venv",
    "venv",
    ".env",
)

REVISION_OUTPUT_MARKERS = (
    "outputs/revision_primary_metrics",
    "outputs\\revision_primary_metrics",
    "outputs/revision_fairness",
    "outputs\\revision_fairness",
    "outputs/revision_fidelity",
    "outputs\\revision_fidelity",
    "outputs/revision_utility",
    "outputs\\revision_utility",
)

KNOWN_REAL_TABLES = {
    "covid_clinical.csv",
    "covid_clinical.xlsx",
    "covid_clinical_preprocessed.csv",
    "covid_clinical_balanced.csv",
    "x_train_scaled.csv",
    "x_test_scaled.csv",
    "y_train.csv",
    "y_test.csv",
}

MIN_SYNTHETIC_ROWS = 10

# -------------------------------------------------------------------------
# Required provenance fields.
#
# An existing synthetic table becomes admissible only if a sidecar JSON proves
# that it originated from this exact locked training partition.
#
# Accepted sidecar filenames:
#
#   <synthetic-file>.provenance.json
#   <stem>_provenance.json
#   <stem>.json
# -------------------------------------------------------------------------

REQUIRED_PROVENANCE_BOOLEAN_FIELDS = [
    "generated_from_training_only",
    "test_rows_excluded",
]

EXPECTED_PROVENANCE_SPLIT_SEED_FIELDS = [
    "source_split_seed",
    "split_seed",
    "random_state",
]

EXPECTED_PROVENANCE_TRAIN_HASH_FIELDS = [
    "source_train_indices_sha256",
    "training_indices_sha256",
    "train_indices_sha256",
]


# =============================================================================
# 2. GENERAL HELPERS
# =============================================================================

def safe_json(value: Any) -> str:
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            default=str,
        )
    except Exception:
        return str(value)


def normalize_name(value: Any) -> str:
    return "".join(
        char
        for char in str(value).strip().lower()
        if char.isalnum()
    )


def relative_path(path: Path) -> str:
    try:
        return str(
            path.relative_to(PROJECT_ROOT)
        )
    except Exception:
        return str(path)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()

    with path.open("rb") as handle:
        while True:
            block = handle.read(
                1024 * 1024
            )

            if not block:
                break

            h.update(block)

    return h.hexdigest()


def sha256_integer_sequence(
    values: Sequence[int],
) -> str:
    """
    Stable SHA256 of ordered integer indices.
    """

    payload = ",".join(
        str(int(value))
        for value in values
    ).encode("utf-8")

    return hashlib.sha256(
        payload
    ).hexdigest()


def write_csv(
    path: Path,
    rows: Sequence[Dict[str, Any]],
    columns: Optional[List[str]] = None,
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if not rows:
        pd.DataFrame(
            columns=columns or []
        ).to_csv(
            path,
            index=False,
            encoding="utf-8-sig",
        )
        return

    df = pd.DataFrame(rows)

    if columns:
        remainder = [
            column
            for column in df.columns
            if column not in columns
        ]

        df = df[
            columns + remainder
        ]

    df.to_csv(
        path,
        index=False,
        encoding="utf-8-sig",
    )


def read_csv_robust(
    path: Path,
) -> pd.DataFrame:
    separator = (
        "\t"
        if path.suffix.lower() == ".tsv"
        else ","
    )

    errors = []

    for encoding in [
        "utf-8-sig",
        "utf-8",
        "cp1252",
        "latin-1",
    ]:
        try:
            return pd.read_csv(
                path,
                encoding=encoding,
                sep=separator,
            )

        except Exception as exc:
            errors.append(
                f"{encoding}: {repr(exc)}"
            )

    raise RuntimeError(
        f"Cannot read table:\n{path}\n"
        + "\n".join(errors)
    )


def read_table(
    path: Path,
) -> Optional[pd.DataFrame]:
    suffix = path.suffix.lower()

    try:
        if suffix in {
            ".csv",
            ".tsv",
        }:
            return read_csv_robust(path)

        if suffix in {
            ".xlsx",
            ".xls",
        }:
            return pd.read_excel(path)

        if suffix == ".parquet":
            return pd.read_parquet(path)

    except Exception:
        return None

    return None


def is_excluded(
    path: Path,
) -> bool:
    try:
        parts = [
            part.lower()
            for part
            in path.relative_to(
                PROJECT_ROOT
            ).parts
        ]
    except Exception:
        parts = [
            part.lower()
            for part in path.parts
        ]

    for part in parts:
        if part in EXCLUDED_DIR_EXACT:
            return True

        if any(
            part.startswith(prefix)
            for prefix in EXCLUDED_DIR_PREFIXES
        ):
            return True

    return False


def is_revision_output(
    path: Path,
) -> bool:
    text = str(path).lower()

    return any(
        marker.lower() in text
        for marker in REVISION_OUTPUT_MARKERS
    )


# =============================================================================
# 3. REAL DATA AND FEATURE SCHEMA
# =============================================================================

def load_real_data(
) -> Tuple[
    pd.DataFrame,
    Path,
    str,
]:
    candidates = []

    if RAW_CSV_PATH.exists():
        try:
            candidates.append(
                (
                    read_csv_robust(
                        RAW_CSV_PATH
                    ),
                    RAW_CSV_PATH,
                    "csv",
                )
            )
        except Exception:
            pass

    if RAW_XLSX_PATH.exists():
        try:
            candidates.append(
                (
                    pd.read_excel(
                        RAW_XLSX_PATH
                    ),
                    RAW_XLSX_PATH,
                    "excel",
                )
            )
        except Exception:
            pass

    for df, path, source_type in candidates:
        if len(df) == EXPECTED_REAL_ROWS:
            return (
                df.copy(),
                path,
                source_type,
            )

    raise RuntimeError(
        "No verified 193-row raw clinical dataset found."
    )


def identify_target_column(
    df: pd.DataFrame,
) -> str:
    normalized = {
        normalize_name(column):
            column
        for column in df.columns
    }

    for candidate in TARGET_CANDIDATES:
        if candidate in df.columns:
            return candidate

        key = normalize_name(
            candidate
        )

        if key in normalized:
            return normalized[
                key
            ]

    raise RuntimeError(
        "Could not identify target/status column."
    )


def load_feature_schema(
) -> List[str]:
    if not FEATURE_SCHEMA_PATH.exists():
        raise FileNotFoundError(
            f"Feature schema missing:\n"
            f"{FEATURE_SCHEMA_PATH}"
        )

    df = read_csv_robust(
        FEATURE_SCHEMA_PATH
    )

    features = [
        str(column)
        for column in df.columns
    ]

    if len(features) != EXPECTED_FEATURE_COUNT:
        raise RuntimeError(
            f"Expected {EXPECTED_FEATURE_COUNT} features; "
            f"found {len(features)}."
        )

    return features


def map_features(
    df: pd.DataFrame,
    feature_names: List[str],
) -> Tuple[
    Optional[pd.DataFrame],
    Dict[str, Any],
]:
    lookup = {}

    duplicates = set()

    for column in df.columns:
        key = normalize_name(
            column
        )

        if key in lookup:
            duplicates.add(key)

        lookup[
            key
        ] = column

    mapped = {}
    missing = []
    ambiguous = []

    for feature in feature_names:
        if feature in df.columns:
            mapped[
                feature
            ] = df[
                feature
            ]
            continue

        key = normalize_name(
            feature
        )

        if key in duplicates:
            ambiguous.append(
                feature
            )
            continue

        if key not in lookup:
            missing.append(
                feature
            )
            continue

        mapped[
            feature
        ] = df[
            lookup[key]
        ]

    diagnostics = {
        "required_features":
            len(feature_names),

        "matched_features":
            len(mapped),

        "missing_features":
            missing,

        "ambiguous_features":
            ambiguous,
    }

    if missing or ambiguous:
        return (
            None,
            diagnostics,
        )

    return (
        pd.DataFrame(mapped),
        diagnostics,
    )


def numeric_dataframe(
    df: pd.DataFrame,
) -> pd.DataFrame:
    result = pd.DataFrame(
        index=df.index
    )

    for column in df.columns:
        result[
            column
        ] = pd.to_numeric(
            df[column],
            errors="coerce",
        )

    return result


def normalize_binary_target(
    series: pd.Series,
) -> pd.Series:
    numeric = pd.to_numeric(
        series,
        errors="coerce",
    )

    if numeric.notna().all():
        unique = sorted(
            numeric.unique()
        )

        if set(unique).issubset(
            {0, 1}
        ):
            return numeric.astype(int)

    mapping = {
        "recovered": 0,
        "survived": 0,
        "survivor": 0,
        "alive": 0,
        "death": 1,
        "dead": 1,
        "deceased": 1,
        "killed": 1,
    }

    converted = (
        series
        .astype(str)
        .str.strip()
        .str.lower()
        .map(mapping)
    )

    if converted.isna().any():
        raise RuntimeError(
            "Target cannot be normalized safely to {0,1}."
        )

    return converted.astype(int)


# =============================================================================
# 4. LOCKED REAL SPLIT
# =============================================================================

def make_locked_split(
    raw_df: pd.DataFrame,
    target_col: str,
) -> Tuple[
    np.ndarray,
    np.ndarray,
    pd.Series,
]:
    y = normalize_binary_target(
        raw_df[target_col]
    )

    source_indices = np.arange(
        len(raw_df),
        dtype=int,
    )

    train_idx, test_idx = train_test_split(
        source_indices,
        test_size=LOCKED_TEST_SIZE,
        random_state=LOCKED_SPLIT_SEED,
        stratify=y.to_numpy(),
    )

    train_idx = np.asarray(
        train_idx,
        dtype=int,
    )

    test_idx = np.asarray(
        test_idx,
        dtype=int,
    )

    return (
        train_idx,
        test_idx,
        y,
    )


def verify_split_integrity(
    train_idx: np.ndarray,
    test_idx: np.ndarray,
    total_rows: int,
) -> List[Dict[str, Any]]:
    overlap = set(
        train_idx.tolist()
    ) & set(
        test_idx.tolist()
    )

    combined = list(
        train_idx
    ) + list(
        test_idx
    )

    rows = [
        {
            "check":
                "train_test_index_overlap",

            "value":
                len(overlap),

            "expected":
                0,

            "status":
                (
                    "PASS"
                    if len(overlap) == 0
                    else "FAIL"
                ),
        },
        {
            "check":
                "combined_index_count",

            "value":
                len(combined),

            "expected":
                total_rows,

            "status":
                (
                    "PASS"
                    if len(combined)
                    == total_rows
                    else "FAIL"
                ),
        },
        {
            "check":
                "unique_combined_index_count",

            "value":
                len(
                    set(combined)
                ),

            "expected":
                total_rows,

            "status":
                (
                    "PASS"
                    if len(
                        set(combined)
                    )
                    == total_rows
                    else "FAIL"
                ),
        },
    ]

    return rows


# =============================================================================
# 5. TRAIN-ONLY PREPROCESSING
# =============================================================================

def fit_training_preprocessor(
    X_train: pd.DataFrame,
) -> Tuple[
    np.ndarray,
    SimpleImputer,
    MinMaxScaler,
    StandardScaler,
    List[Dict[str, Any]],
]:
    imputer = SimpleImputer(
        strategy="median"
    )

    minmax = MinMaxScaler()

    standard = StandardScaler()

    X_imputed = imputer.fit_transform(
        X_train
    )

    X_minmax = minmax.fit_transform(
        X_imputed
    )

    X_final = standard.fit_transform(
        X_minmax
    )

    audit = []

    for index, feature in enumerate(
        X_train.columns
    ):
        audit.append(
            {
                "feature":
                    feature,

                "missing_in_locked_train":
                    int(
                        X_train[
                            feature
                        ].isna().sum()
                    ),

                "imputation_median":
                    float(
                        imputer.statistics_[
                            index
                        ]
                    ),

                "minmax_data_min":
                    float(
                        minmax.data_min_[
                            index
                        ]
                    ),

                "minmax_data_max":
                    float(
                        minmax.data_max_[
                            index
                        ]
                    ),

                "standard_mean":
                    float(
                        standard.mean_[
                            index
                        ]
                    ),

                "standard_scale":
                    float(
                        standard.scale_[
                            index
                        ]
                    ),

                "fit_scope":
                    "LOCKED_REAL_TRAIN_ONLY",
            }
        )

    return (
        X_final,
        imputer,
        minmax,
        standard,
        audit,
    )


def apply_training_preprocessor(
    X: pd.DataFrame,
    imputer: SimpleImputer,
    minmax: MinMaxScaler,
    standard: StandardScaler,
) -> np.ndarray:
    X_imputed = imputer.transform(
        X
    )

    X_minmax = minmax.transform(
        X_imputed
    )

    return standard.transform(
        X_minmax
    )


# =============================================================================
# 6. CLASSIFIER
# =============================================================================

def load_classifier_template():
    if not PRESERVED_CLASSIFIER_PATH.exists():
        raise FileNotFoundError(
            f"Preserved classifier missing:\n"
            f"{PRESERVED_CLASSIFIER_PATH}"
        )

    model = joblib.load(
        PRESERVED_CLASSIFIER_PATH
    )

    return model


def train_classifier(
    template,
    X_train: np.ndarray,
    y_train: np.ndarray,
):
    model = clone(
        template
    )

    model.fit(
        X_train,
        y_train,
    )

    return model


def get_positive_score(
    model,
    X: np.ndarray,
) -> Tuple[
    np.ndarray,
    str,
]:
    if hasattr(
        model,
        "predict_proba",
    ):
        probabilities = model.predict_proba(
            X
        )

        classes = list(
            model.classes_
        )

        if 1 not in classes:
            raise RuntimeError(
                "Positive class 1 absent from classifier classes_."
            )

        positive_index = classes.index(
            1
        )

        return (
            np.asarray(
                probabilities[
                    :,
                    positive_index
                ],
                dtype=float,
            ),
            "predict_proba_positive_class",
        )

    if hasattr(
        model,
        "decision_function",
    ):
        score = np.asarray(
            model.decision_function(
                X
            ),
            dtype=float,
        )

        return (
            score,
            "decision_function",
        )

    raise RuntimeError(
        "Classifier has neither predict_proba nor decision_function."
    )


def compute_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    y_score: np.ndarray,
) -> Tuple[
    Dict[str, Any],
    Dict[str, Any],
]:
    cm = confusion_matrix(
        y_true,
        y_pred,
        labels=[
            0,
            1,
        ],
    )

    tn, fp, fn, tp = cm.ravel()

    specificity = (
        tn / (
            tn + fp
        )
        if (
            tn + fp
        ) > 0
        else np.nan
    )

    metrics = {
        "accuracy":
            accuracy_score(
                y_true,
                y_pred,
            ),

        "precision":
            precision_score(
                y_true,
                y_pred,
                zero_division=0,
            ),

        "recall_sensitivity":
            recall_score(
                y_true,
                y_pred,
                zero_division=0,
            ),

        "specificity":
            specificity,

        "f1":
            f1_score(
                y_true,
                y_pred,
                zero_division=0,
            ),

        "roc_auc":
            roc_auc_score(
                y_true,
                y_score,
            ),
    }

    confusion = {
        "tn":
            int(tn),

        "fp":
            int(fp),

        "fn":
            int(fn),

        "tp":
            int(tp),

        "total":
            int(
                tn
                + fp
                + fn
                + tp
            ),
    }

    return (
        metrics,
        confusion,
    )


# =============================================================================
# 7. SYNTHETIC TABLE DISCOVERY
# =============================================================================

def find_target_in_table(
    df: pd.DataFrame,
) -> Optional[str]:
    normalized = {
        normalize_name(column):
            column
        for column in df.columns
    }

    for candidate in TARGET_CANDIDATES:
        if candidate in df.columns:
            return candidate

        key = normalize_name(
            candidate
        )

        if key in normalized:
            return normalized[
                key
            ]

    return None


def synthetic_hint_score(
    path: Path,
) -> int:
    lower = str(path).lower()

    return sum(
        int(
            hint in lower
        )
        for hint in SYNTHETIC_HINTS
    )


def sidecar_candidates(
    table_path: Path,
) -> List[Path]:
    candidates = [
        Path(
            str(table_path)
            + ".provenance.json"
        ),

        table_path.with_name(
            table_path.stem
            + "_provenance.json"
        ),

        table_path.with_suffix(
            ".json"
        ),
    ]

    unique = []

    seen = set()

    for candidate in candidates:
        key = str(
            candidate
        ).lower()

        if key not in seen:
            seen.add(key)
            unique.append(
                candidate
            )

    return unique


def read_json_file(
    path: Path,
) -> Optional[Dict[str, Any]]:
    try:
        with path.open(
            "r",
            encoding="utf-8",
        ) as handle:
            obj = json.load(handle)

        if isinstance(
            obj,
            dict,
        ):
            return obj

    except Exception:
        return None

    return None


def get_first_field(
    obj: Dict[str, Any],
    candidates: Sequence[str],
) -> Tuple[
    Optional[Any],
    Optional[str],
]:
    normalized = {
        normalize_name(key):
            key
        for key in obj.keys()
    }

    for candidate in candidates:
        if candidate in obj:
            return (
                obj[candidate],
                candidate,
            )

        key = normalize_name(
            candidate
        )

        if key in normalized:
            actual = normalized[
                key
            ]

            return (
                obj[actual],
                actual,
            )

    return (
        None,
        None,
    )


def discover_synthetic_candidates(
    feature_names: List[str],
) -> Tuple[
    List[Dict[str, Any]],
    Dict[str, Dict[str, Any]],
]:
    inventory = []

    loaded = {}

    for path in PROJECT_ROOT.rglob("*"):
        if not path.is_file():
            continue

        if is_excluded(path):
            continue

        if is_revision_output(path):
            continue

        if (
            path.suffix.lower()
            not in TABULAR_EXTENSIONS
        ):
            continue

        if (
            path.name.lower()
            in KNOWN_REAL_TABLES
        ):
            continue

        hint_score = synthetic_hint_score(
            path
        )

        if hint_score <= 0:
            continue

        df = read_table(
            path
        )

        if df is None:
            continue

        (
            X_candidate,
            mapping_diagnostics,
        ) = map_features(
            df,
            feature_names,
        )

        target_col = find_target_in_table(
            df
        )

        full_feature_schema = (
            X_candidate is not None
        )

        binary_target_valid = False

        if target_col is not None:
            try:
                _ = normalize_binary_target(
                    df[
                        target_col
                    ]
                )

                binary_target_valid = True

            except Exception:
                binary_target_valid = False

        relative = relative_path(
            path
        )

        inventory.append(
            {
                "file":
                    relative,

                "rows":
                    len(df),

                "columns":
                    len(df.columns),

                "synthetic_hint_score":
                    hint_score,

                "matched_features":
                    mapping_diagnostics[
                        "matched_features"
                    ],

                "full_51_feature_schema":
                    int(
                        full_feature_schema
                    ),

                "target_column":
                    (
                        target_col
                        if target_col
                        is not None
                        else ""
                    ),

                "valid_binary_target":
                    int(
                        binary_target_valid
                    ),

                "potential_utility_candidate":
                    int(
                        full_feature_schema
                        and
                        binary_target_valid
                        and
                        len(df)
                        >= MIN_SYNTHETIC_ROWS
                    ),

                "sha256":
                    sha256_file(path),
            }
        )

        if (
            full_feature_schema
            and
            binary_target_valid
            and
            len(df)
            >= MIN_SYNTHETIC_ROWS
        ):
            loaded[
                relative
            ] = {
                "path":
                    path,

                "df":
                    df,

                "X":
                    X_candidate,

                "target_col":
                    target_col,
            }

    return (
        inventory,
        loaded,
    )


# =============================================================================
# 8. SYNTHETIC PROVENANCE AUDIT
# =============================================================================

def audit_synthetic_provenance(
    synthetic_candidates: Dict[
        str,
        Dict[str, Any],
    ],
    train_indices_hash: str,
) -> Tuple[
    List[Dict[str, Any]],
    List[Dict[str, Any]],
]:
    audit_rows = []

    admissible = []

    for relative, candidate in synthetic_candidates.items():
        table_path = candidate[
            "path"
        ]

        sidecars = [
            path
            for path
            in sidecar_candidates(
                table_path
            )
            if path.exists()
        ]

        if not sidecars:
            audit_rows.append(
                {
                    "synthetic_table":
                        relative,

                    "sidecar":
                        "",

                    "generated_from_training_only":
                        False,

                    "test_rows_excluded":
                        False,

                    "split_seed_verified":
                        False,

                    "training_indices_hash_verified":
                        False,

                    "overall_admissible":
                        False,

                    "status":
                        "NO_PROVENANCE_SIDECAR",
                }
            )

            continue

        any_admissible = False

        for sidecar_path in sidecars:
            provenance = read_json_file(
                sidecar_path
            )

            if provenance is None:
                audit_rows.append(
                    {
                        "synthetic_table":
                            relative,

                        "sidecar":
                            relative_path(
                                sidecar_path
                            ),

                        "generated_from_training_only":
                            False,

                        "test_rows_excluded":
                            False,

                        "split_seed_verified":
                            False,

                        "training_indices_hash_verified":
                            False,

                        "overall_admissible":
                            False,

                        "status":
                            "UNREADABLE_OR_NONOBJECT_JSON",
                    }
                )

                continue

            train_only_value, train_only_field = (
                get_first_field(
                    provenance,
                    [
                        "generated_from_training_only"
                    ],
                )
            )

            test_excluded_value, test_excluded_field = (
                get_first_field(
                    provenance,
                    [
                        "test_rows_excluded"
                    ],
                )
            )

            seed_value, seed_field = (
                get_first_field(
                    provenance,
                    EXPECTED_PROVENANCE_SPLIT_SEED_FIELDS,
                )
            )

            hash_value, hash_field = (
                get_first_field(
                    provenance,
                    EXPECTED_PROVENANCE_TRAIN_HASH_FIELDS,
                )
            )

            generated_train_only = (
                train_only_value is True
            )

            test_rows_excluded = (
                test_excluded_value is True
            )

            try:
                seed_verified = (
                    int(seed_value)
                    ==
                    LOCKED_SPLIT_SEED
                )
            except Exception:
                seed_verified = False

            hash_verified = (
                isinstance(
                    hash_value,
                    str,
                )
                and
                hash_value.strip().lower()
                ==
                train_indices_hash.lower()
            )

            overall = all(
                [
                    generated_train_only,
                    test_rows_excluded,
                    seed_verified,
                    hash_verified,
                ]
            )

            audit_rows.append(
                {
                    "synthetic_table":
                        relative,

                    "sidecar":
                        relative_path(
                            sidecar_path
                        ),

                    "generated_from_training_only":
                        generated_train_only,

                    "generated_from_training_only_field":
                        train_only_field or "",

                    "test_rows_excluded":
                        test_rows_excluded,

                    "test_rows_excluded_field":
                        test_excluded_field or "",

                    "split_seed":
                        seed_value,

                    "split_seed_field":
                        seed_field or "",

                    "split_seed_verified":
                        seed_verified,

                    "training_indices_sha256":
                        hash_value,

                    "training_indices_hash_field":
                        hash_field or "",

                    "expected_training_indices_sha256":
                        train_indices_hash,

                    "training_indices_hash_verified":
                        hash_verified,

                    "overall_admissible":
                        overall,

                    "status":
                        (
                            "PASS"
                            if overall
                            else "FAIL"
                        ),
                }
            )

            if overall:
                any_admissible = True

                admissible.append(
                    {
                        "synthetic_table":
                            relative,

                        "sidecar":
                            relative_path(
                                sidecar_path
                            ),

                        "table_sha256":
                            sha256_file(
                                table_path
                            ),

                        "training_indices_sha256":
                            train_indices_hash,

                        "status":
                            "ADMISSIBLE",
                    }
                )

                break

        if not any_admissible:
            pass

    return (
        audit_rows,
        admissible,
    )


# =============================================================================
# 9. EVALUATION CONDITION
# =============================================================================

def evaluate_training_condition(
    condition_name: str,
    training_source: str,
    X_train_processed: np.ndarray,
    y_train: np.ndarray,
    X_test_processed: np.ndarray,
    y_test: np.ndarray,
    test_source_indices: np.ndarray,
    classifier_template,
) -> Tuple[
    Dict[str, Any],
    Dict[str, Any],
    List[Dict[str, Any]],
]:
    model = train_classifier(
        classifier_template,
        X_train_processed,
        y_train,
    )

    y_pred = np.asarray(
        model.predict(
            X_test_processed
        ),
        dtype=int,
    )

    y_score, score_source = get_positive_score(
        model,
        X_test_processed,
    )

    metrics, confusion = compute_metrics(
        y_test,
        y_pred,
        y_score,
    )

    metric_row = {
        "condition":
            condition_name,

        "training_source":
            training_source,

        "n_training":
            len(y_train),

        "n_common_real_test":
            len(y_test),

        **metrics,
    }

    confusion_row = {
        "condition":
            condition_name,

        "training_source":
            training_source,

        **confusion,
    }

    prediction_rows = []

    for position in range(
        len(y_test)
    ):
        prediction_rows.append(
            {
                "condition":
                    condition_name,

                "training_source":
                    training_source,

                "common_test_position":
                    position,

                "original_source_row_index":
                    int(
                        test_source_indices[
                            position
                        ]
                    ),

                "y_true":
                    int(
                        y_test[
                            position
                        ]
                    ),

                "y_pred":
                    int(
                        y_pred[
                            position
                        ]
                    ),

                "correct":
                    int(
                        y_true_equal(
                            y_test[position],
                            y_pred[position],
                        )
                    ),

                "y_score_positive":
                    float(
                        y_score[
                            position
                        ]
                    ),

                "score_source":
                    score_source,
            }
        )

    return (
        metric_row,
        confusion_row,
        prediction_rows,
    )


def y_true_equal(
    y_true: Any,
    y_pred: Any,
) -> bool:
    return int(
        y_true
    ) == int(
        y_pred
    )


# =============================================================================
# 10. MAIN
# =============================================================================

def main() -> None:
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    print(
        "=" * 100
    )

    print(
        "HFAGM - COMMON UNTOUCHED REAL TEST UTILITY"
    )

    print(
        "=" * 100
    )

    print(
        f"\nPython: {sys.version.split()[0]}"
    )

    print(
        f"NumPy: {np.__version__}"
    )

    print(
        f"pandas: {pd.__version__}"
    )

    print(
        f"SciPy: {scipy.__version__}"
    )

    print(
        f"scikit-learn: {sklearn.__version__}"
    )

    # -----------------------------------------------------------------
    # Load source.
    # -----------------------------------------------------------------

    raw_df, raw_path, raw_type = (
        load_real_data()
    )

    target_col = identify_target_column(
        raw_df
    )

    feature_names = load_feature_schema()

    X_real, mapping_diagnostics = (
        map_features(
            raw_df,
            feature_names,
        )
    )

    if X_real is None:
        raise RuntimeError(
            "Could not map all 51 predictors to raw data.\n"
            + safe_json(
                mapping_diagnostics
            )
        )

    X_real = numeric_dataframe(
        X_real
    )

    # -----------------------------------------------------------------
    # Locked common real test split.
    # -----------------------------------------------------------------

    (
        train_idx,
        test_idx,
        y_all,
    ) = make_locked_split(
        raw_df,
        target_col,
    )

    split_audit = verify_split_integrity(
        train_idx,
        test_idx,
        len(raw_df),
    )

    if any(
        row[
            "status"
        ] != "PASS"
        for row in split_audit
    ):
        raise RuntimeError(
            "Locked split integrity audit failed."
        )

    train_indices_hash = (
        sha256_integer_sequence(
            train_idx.tolist()
        )
    )

    test_indices_hash = (
        sha256_integer_sequence(
            test_idx.tolist()
        )
    )

    split_manifest = [
        {
            "split_name":
                "locked_common_real_test",

            "random_state":
                LOCKED_SPLIT_SEED,

            "test_size_fraction":
                LOCKED_TEST_SIZE,

            "total_real_rows":
                len(raw_df),

            "train_rows":
                len(train_idx),

            "test_rows":
                len(test_idx),

            "train_class_0":
                int(
                    np.sum(
                        y_all.iloc[
                            train_idx
                        ].to_numpy()
                        == 0
                    )
                ),

            "train_class_1":
                int(
                    np.sum(
                        y_all.iloc[
                            train_idx
                        ].to_numpy()
                        == 1
                    )
                ),

            "test_class_0":
                int(
                    np.sum(
                        y_all.iloc[
                            test_idx
                        ].to_numpy()
                        == 0
                    )
                ),

            "test_class_1":
                int(
                    np.sum(
                        y_all.iloc[
                            test_idx
                        ].to_numpy()
                        == 1
                    )
                ),

            "train_indices_sha256":
                train_indices_hash,

            "test_indices_sha256":
                test_indices_hash,

            "purpose":
                (
                    "single locked untouched real test set "
                    "for every downstream utility condition"
                ),
        }
    ]

    write_csv(
        OUTPUT_DIR
        / "locked_split_manifest.csv",
        split_manifest,
    )

    write_csv(
        OUTPUT_DIR
        / "locked_train_indices.csv",
        [
            {
                "train_position":
                    position,

                "original_source_row_index":
                    int(index),
            }
            for position, index
            in enumerate(train_idx)
        ],
    )

    write_csv(
        OUTPUT_DIR
        / "locked_test_indices.csv",
        [
            {
                "test_position":
                    position,

                "original_source_row_index":
                    int(index),
            }
            for position, index
            in enumerate(test_idx)
        ],
    )

    write_csv(
        OUTPUT_DIR
        / "common_test_integrity_audit.csv",
        split_audit,
    )

    # -----------------------------------------------------------------
    # Extract train/test data.
    # -----------------------------------------------------------------

    X_train_real = X_real.iloc[
        train_idx
    ].reset_index(
        drop=True
    )

    X_test_real = X_real.iloc[
        test_idx
    ].reset_index(
        drop=True
    )

    y_train_real = y_all.iloc[
        train_idx
    ].to_numpy(
        dtype=int
    )

    y_test_real = y_all.iloc[
        test_idx
    ].to_numpy(
        dtype=int
    )

    # Save locked test with source indices.
    locked_test_df = (
        raw_df.iloc[
            test_idx
        ]
        .copy()
        .reset_index(
            drop=False
        )
        .rename(
            columns={
                "index":
                    "original_source_row_index"
            }
        )
    )

    locked_test_df.to_csv(
        OUTPUT_DIR
        / "locked_test_data.csv",
        index=False,
        encoding="utf-8-sig",
    )

    # -----------------------------------------------------------------
    # Fit preprocessing ONLY on locked real train.
    # -----------------------------------------------------------------

    (
        X_train_real_processed,
        imputer,
        minmax,
        standard,
        preprocessing_audit,
    ) = fit_training_preprocessor(
        X_train_real
    )

    X_test_real_processed = (
        apply_training_preprocessor(
            X_test_real,
            imputer,
            minmax,
            standard,
        )
    )

    write_csv(
        OUTPUT_DIR
        / "preprocessing_audit.csv",
        preprocessing_audit,
    )

    # -----------------------------------------------------------------
    # Real training audit.
    # -----------------------------------------------------------------

    real_training_audit = [
        {
            "condition":
                "real_training_unbalanced",

            "source":
                str(raw_path),

            "training_rows":
                len(train_idx),

            "test_rows":
                len(test_idx),

            "preprocessing_fit_scope":
                "LOCKED_REAL_TRAIN_ONLY",

            "training_only_oversampling":
                False,

            "test_used_during_preprocessing_fit":
                False,

            "test_used_during_model_fit":
                False,

            "test_used_during_model_selection":
                False,

            "status":
                "VALID_COMMON_TEST_REFERENCE",
        }
    ]

    write_csv(
        OUTPUT_DIR
        / "real_training_data_audit.csv",
        real_training_audit,
    )

    # -----------------------------------------------------------------
    # Load preserved classifier architecture.
    # -----------------------------------------------------------------

    classifier_template = (
        load_classifier_template()
    )

    classifier_provenance = [
        {
            "source_model":
                str(
                    PRESERVED_CLASSIFIER_PATH
                ),

            "source_sha256":
                sha256_file(
                    PRESERVED_CLASSIFIER_PATH
                ),

            "template_class":
                type(
                    classifier_template
                ).__name__,

            "template_parameters":
                safe_json(
                    classifier_template.get_params(
                        deep=True
                    )
                ),

            "operation":
                (
                    "clone architecture and retrain separately "
                    "for each admissible training condition"
                ),

            "historical_fitted_weights_reused":
                False,
        }
    ]

    write_csv(
        OUTPUT_DIR
        / "classifier_provenance.csv",
        classifier_provenance,
    )

    # -----------------------------------------------------------------
    # Evaluate real training reference.
    # -----------------------------------------------------------------

    metrics_rows = []

    confusion_rows = []

    prediction_rows = []

    (
        real_metric,
        real_confusion,
        real_predictions,
    ) = evaluate_training_condition(
        condition_name=(
            "real_training_unbalanced"
        ),
        training_source=(
            relative_path(
                raw_path
            )
        ),
        X_train_processed=(
            X_train_real_processed
        ),
        y_train=y_train_real,
        X_test_processed=(
            X_test_real_processed
        ),
        y_test=y_test_real,
        test_source_indices=test_idx,
        classifier_template=(
            classifier_template
        ),
    )

    metrics_rows.append(
        real_metric
    )

    confusion_rows.append(
        real_confusion
    )

    prediction_rows.extend(
        real_predictions
    )

    # -----------------------------------------------------------------
    # Discover synthetic training candidates.
    # -----------------------------------------------------------------

    (
        synthetic_inventory,
        synthetic_candidates,
    ) = discover_synthetic_candidates(
        feature_names
    )

    write_csv(
        OUTPUT_DIR
        / "synthetic_candidate_inventory.csv",
        synthetic_inventory,
    )

    (
        synthetic_provenance_rows,
        admissible_rows,
    ) = audit_synthetic_provenance(
        synthetic_candidates,
        train_indices_hash,
    )

    write_csv(
        OUTPUT_DIR
        / "synthetic_provenance_audit.csv",
        synthetic_provenance_rows,
    )

    write_csv(
        OUTPUT_DIR
        / "admissible_synthetic_training_sets.csv",
        admissible_rows,
    )

    # -----------------------------------------------------------------
    # Evaluate synthetic conditions ONLY if provenance is complete.
    # -----------------------------------------------------------------

    admissible_names = {
        row[
            "synthetic_table"
        ]
        for row in admissible_rows
    }

    synthetic_evaluated = 0

    for synthetic_name in sorted(
        admissible_names
    ):
        candidate = (
            synthetic_candidates[
                synthetic_name
            ]
        )

        X_synth = numeric_dataframe(
            candidate[
                "X"
            ]
        )

        y_synth = normalize_binary_target(
            candidate[
                "df"
            ][
                candidate[
                    "target_col"
                ]
            ]
        ).to_numpy(
            dtype=int
        )

        # -------------------------------------------------------------
        # Apply EXACT SAME transform fitted only on locked REAL training.
        #
        # We do not fit preprocessing independently on synthetic data,
        # because that would alter the test-coordinate system between
        # conditions.
        # -------------------------------------------------------------

        X_synth_processed = (
            apply_training_preprocessor(
                X_synth,
                imputer,
                minmax,
                standard,
            )
        )

        condition_name = (
            "synthetic_training_verified::"
            + Path(
                synthetic_name
            ).stem
        )

        (
            metric_row,
            confusion_row,
            predictions,
        ) = evaluate_training_condition(
            condition_name=condition_name,
            training_source=synthetic_name,
            X_train_processed=(
                X_synth_processed
            ),
            y_train=y_synth,
            X_test_processed=(
                X_test_real_processed
            ),
            y_test=y_test_real,
            test_source_indices=test_idx,
            classifier_template=(
                classifier_template
            ),
        )

        metrics_rows.append(
            metric_row
        )

        confusion_rows.append(
            confusion_row
        )

        prediction_rows.extend(
            predictions
        )

        synthetic_evaluated += 1

    # -----------------------------------------------------------------
    # Integrity check: every condition must use exactly same test rows.
    # -----------------------------------------------------------------

    if prediction_rows:
        pred_df = pd.DataFrame(
            prediction_rows
        )

        expected_test_sequence = (
            test_idx.tolist()
        )

        for condition, group in pred_df.groupby(
            "condition",
            sort=False,
        ):
            group = group.sort_values(
                "common_test_position"
            )

            observed = (
                group[
                    "original_source_row_index"
                ]
                .astype(int)
                .tolist()
            )

            if observed != expected_test_sequence:
                raise RuntimeError(
                    "Common-test invariant violated for condition: "
                    f"{condition}"
                )

    # -----------------------------------------------------------------
    # Save results.
    # -----------------------------------------------------------------

    write_csv(
        OUTPUT_DIR
        / "utility_metrics.csv",
        metrics_rows,
    )

    write_csv(
        OUTPUT_DIR
        / "utility_confusion_matrices.csv",
        confusion_rows,
    )

    write_csv(
        OUTPUT_DIR
        / "utility_predictions.csv",
        prediction_rows,
    )

    # -----------------------------------------------------------------
    # Comparison.
    # -----------------------------------------------------------------

    comparison_rows = []

    if synthetic_evaluated > 0:
        real_reference = metrics_rows[
            0
        ]

        for row in metrics_rows[
            1:
        ]:
            comparison_rows.append(
                {
                    "reference_condition":
                        "real_training_unbalanced",

                    "comparison_condition":
                        row[
                            "condition"
                        ],

                    "common_test_n":
                        row[
                            "n_common_real_test"
                        ],

                    "delta_accuracy":
                        (
                            row[
                                "accuracy"
                            ]
                            -
                            real_reference[
                                "accuracy"
                            ]
                        ),

                    "delta_f1":
                        (
                            row[
                                "f1"
                            ]
                            -
                            real_reference[
                                "f1"
                            ]
                        ),

                    "delta_roc_auc":
                        (
                            row[
                                "roc_auc"
                            ]
                            -
                            real_reference[
                                "roc_auc"
                            ]
                        ),

                    "interpretation":
                        (
                            "descriptive same-test difference; "
                            "no significance claim from one locked split"
                        ),
                }
            )

    write_csv(
        OUTPUT_DIR
        / "utility_comparison.csv",
        comparison_rows,
    )

    # -----------------------------------------------------------------
    # Verdict.
    # -----------------------------------------------------------------

    if synthetic_evaluated == 0:
        verdict = (
            "SYNTHETIC_UTILITY_NOT_RECOMPUTABLE_FROM_RECOVERED_ARTIFACTS"
        )

        synthetic_status = (
            "NOT_RECOMPUTABLE"
        )

        manuscript_action = (
            "Retain the leakage-safe real-data reference benchmark, but "
            "remove historical real-vs-synthetic downstream-utility claims "
            "because no synthetic training dataset with training-only "
            "provenance is recoverable. Do not substitute newly generated "
            "synthetic data into the historical comparison."
        )

        reviewer_action = (
            "Explain that the revised audit established a common locked "
            "real-test protocol, but the submitted synthetic conditions "
            "could not be reproduced from recoverable training-only "
            "synthetic artifacts; unsupported historical comparisons are "
            "therefore removed."
        )

    else:
        verdict = (
            "COMMON_REAL_TEST_SYNTHETIC_UTILITY_RECOMPUTED"
        )

        synthetic_status = (
            "RECOMPUTED"
        )

        manuscript_action = (
            "Replace historical utility comparisons with the recomputed "
            "same-test metrics only. State that all conditions were trained "
            "separately and evaluated on the identical locked real test set."
        )

        reviewer_action = (
            "Report the corrected controlled downstream-utility experiment."
        )

    verdict_rows = [
        {
            "verdict":
                verdict,

            "locked_split_seed":
                LOCKED_SPLIT_SEED,

            "locked_real_train_n":
                len(train_idx),

            "locked_real_test_n":
                len(test_idx),

            "real_reference_computed":
                True,

            "synthetic_candidate_tables":
                len(
                    synthetic_candidates
                ),

            "admissible_synthetic_training_sets":
                len(
                    admissible_rows
                ),

            "synthetic_conditions_evaluated":
                synthetic_evaluated,

            "synthetic_utility_status":
                synthetic_status,

            "common_test_used_for_all_conditions":
                True,

            "historical_different_test_sizes_accepted":
                False,

            "manuscript_action":
                manuscript_action,

            "reviewer_response_action":
                reviewer_action,
        }
    ]

    write_csv(
        OUTPUT_DIR
        / "utility_verdict.csv",
        verdict_rows,
    )

    # -----------------------------------------------------------------
    # Provenance.
    # -----------------------------------------------------------------

    provenance = [
        {
            "generated":
                datetime.now().isoformat(
                    timespec="seconds"
                ),

            "script":
                "05_common_real_test_utility.py",

            "real_source":
                str(raw_path),

            "real_source_sha256":
                sha256_file(
                    raw_path
                ),

            "feature_schema_source":
                str(
                    FEATURE_SCHEMA_PATH
                ),

            "feature_schema_sha256":
                sha256_file(
                    FEATURE_SCHEMA_PATH
                ),

            "classifier_template":
                str(
                    PRESERVED_CLASSIFIER_PATH
                ),

            "classifier_template_sha256":
                sha256_file(
                    PRESERVED_CLASSIFIER_PATH
                ),

            "split_seed":
                LOCKED_SPLIT_SEED,

            "test_fraction":
                LOCKED_TEST_SIZE,

            "train_indices_sha256":
                train_indices_hash,

            "test_indices_sha256":
                test_indices_hash,

            "preprocessing_fit_scope":
                "LOCKED_REAL_TRAIN_ONLY",

            "synthetic_data_generated":
                False,

            "new_generative_model_trained":
                False,

            "same_real_test_for_every_condition":
                True,

            "python_version":
                sys.version,

            "numpy_version":
                np.__version__,

            "pandas_version":
                pd.__version__,

            "scipy_version":
                scipy.__version__,

            "sklearn_version":
                sklearn.__version__,
        }
    ]

    write_csv(
        OUTPUT_DIR
        / "utility_provenance.csv",
        provenance,
    )

    # -----------------------------------------------------------------
    # Human-readable summary.
    # -----------------------------------------------------------------

    lines = [
        "=" * 100,
        "HFAGM - COMMON UNTOUCHED REAL TEST UTILITY AUDIT",
        "=" * 100,
        "",
        f"Generated: {provenance[0]['generated']}",
        "",
        "CONTROLLED PROTOCOL",
        "-" * 100,
        f"Raw real dataset: {raw_path}",
        f"Total real records: {len(raw_df)}",
        f"Predictors: {len(feature_names)}",
        f"Target: {target_col}",
        f"Locked split random state: {LOCKED_SPLIT_SEED}",
        f"Locked real training rows: {len(train_idx)}",
        f"Locked untouched real test rows: {len(test_idx)}",
        (
            "Preprocessing fit scope: locked real training partition only."
        ),
        (
            "Every admissible condition is evaluated on exactly the same "
            "locked real test records."
        ),
        "",
        "REAL TRAINING REFERENCE",
        "-" * 100,
    ]

    for key in [
        "accuracy",
        "precision",
        "recall_sensitivity",
        "specificity",
        "f1",
        "roc_auc",
    ]:
        lines.append(
            f"{key}: {real_metric[key]:.10f}"
        )

    lines.extend(
        [
            "",
            "REAL REFERENCE CONFUSION MATRIX",
            "-" * 100,
            f"TN: {real_confusion['tn']}",
            f"FP: {real_confusion['fp']}",
            f"FN: {real_confusion['fn']}",
            f"TP: {real_confusion['tp']}",
            (
                f"Total common real test observations: "
                f"{real_confusion['total']}"
            ),
            "",
            "SYNTHETIC TRAINING AUDIT",
            "-" * 100,
            (
                f"Potential labeled 51-feature synthetic candidates: "
                f"{len(synthetic_candidates)}"
            ),
            (
                f"Candidates passing strict training-only provenance: "
                f"{len(admissible_rows)}"
            ),
            (
                f"Synthetic conditions evaluated: "
                f"{synthetic_evaluated}"
            ),
            "",
        ]
    )

    if synthetic_evaluated == 0:
        lines.extend(
            [
                (
                    "No recovered synthetic training dataset satisfied the "
                    "required provenance conditions."
                ),
                (
                    "Therefore no real-vs-synthetic downstream utility "
                    "difference is reported."
                ),
                (
                    "This script intentionally does NOT generate replacement "
                    "synthetic data."
                ),
                "",
            ]
        )
    else:
        lines.append(
            "RECOMPUTED SYNTHETIC UTILITY CONDITIONS"
        )

        lines.append(
            "-" * 100
        )

        for metric in metrics_rows[
            1:
        ]:
            lines.extend(
                [
                    metric[
                        "condition"
                    ],

                    (
                        f"  Training n: "
                        f"{metric['n_training']}"
                    ),

                    (
                        f"  Common test n: "
                        f"{metric['n_common_real_test']}"
                    ),

                    (
                        f"  Accuracy: "
                        f"{metric['accuracy']:.10f}"
                    ),

                    (
                        f"  F1: "
                        f"{metric['f1']:.10f}"
                    ),

                    (
                        f"  ROC-AUC: "
                        f"{metric['roc_auc']:.10f}"
                    ),

                    "",
                ]
            )

    lines.extend(
        [
            "FINAL VERDICT",
            "-" * 100,
            verdict,
            "",
            "MANUSCRIPT ACTION",
            "-" * 100,
            manuscript_action,
            "",
            "REVIEWER RESPONSE CONSEQUENCE",
            "-" * 100,
            reviewer_action,
            "",
            "INTERPRETATION LIMITATIONS",
            "-" * 100,
            (
                "This is one locked real-test experiment. It establishes a "
                "controlled comparison framework but should not be used by "
                "itself to claim statistical significance."
            ),
            (
                "Repeated-seed uncertainty or paired resampling statistics "
                "must be handled separately if a valid synthetic condition "
                "becomes available."
            ),
            (
                "The 193-patient real dataset remains the independent "
                "information source; synthetic sample count does not increase "
                "the number of independent patients."
            ),
            "",
            "PRIMARY OUTPUTS",
            "-" * 100,
            "locked_split_manifest.csv",
            "locked_train_indices.csv",
            "locked_test_indices.csv",
            "locked_test_data.csv",
            "real_training_data_audit.csv",
            "preprocessing_audit.csv",
            "common_test_integrity_audit.csv",
            "classifier_provenance.csv",
            "synthetic_candidate_inventory.csv",
            "synthetic_provenance_audit.csv",
            "admissible_synthetic_training_sets.csv",
            "utility_predictions.csv",
            "utility_confusion_matrices.csv",
            "utility_metrics.csv",
            "utility_comparison.csv",
            "utility_verdict.csv",
            "utility_provenance.csv",
            "",
            "=" * 100,
        ]
    )

    summary_path = (
        OUTPUT_DIR
        / "common_real_test_utility_summary.txt"
    )

    summary_path.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    # -----------------------------------------------------------------
    # Console.
    # -----------------------------------------------------------------

    print(
        "\n" + "=" * 100
    )

    print(
        "05 COMPLETE"
    )

    print(
        "=" * 100
    )

    print(
        "\nLocked common real test:"
    )

    print(
        f"  Train n = {len(train_idx)}"
    )

    print(
        f"  Test n  = {len(test_idx)}"
    )

    print(
        "\nReal training reference:"
    )

    print(
        f"  Accuracy = "
        f"{real_metric['accuracy']:.10f}"
    )

    print(
        f"  F1       = "
        f"{real_metric['f1']:.10f}"
    )

    print(
        f"  ROC-AUC  = "
        f"{real_metric['roc_auc']:.10f}"
    )

    print(
        "\nSynthetic audit:"
    )

    print(
        f"  Potential utility candidates = "
        f"{len(synthetic_candidates)}"
    )

    print(
        f"  Admissible provenance-valid candidates = "
        f"{len(admissible_rows)}"
    )

    print(
        f"  Synthetic conditions evaluated = "
        f"{synthetic_evaluated}"
    )

    print(
        "\nFINAL VERDICT:"
    )

    print(
        verdict
    )

    print(
        "\nResults written to:"
    )

    print(
        OUTPUT_DIR
    )

    print(
        "\nUpload these files first:"
    )

    for filename in [
        "common_real_test_utility_summary.txt",
        "utility_verdict.csv",
        "utility_metrics.csv",
        "utility_confusion_matrices.csv",
        "utility_predictions.csv",
        "locked_split_manifest.csv",
        "common_test_integrity_audit.csv",
        "synthetic_candidate_inventory.csv",
        "synthetic_provenance_audit.csv",
        "admissible_synthetic_training_sets.csv",
        "classifier_provenance.csv",
        "utility_provenance.csv",
    ]:
        print(
            OUTPUT_DIR
            / filename
        )


if __name__ == "__main__":
    try:
        main()

    except Exception as exc:
        print(
            "\n" + "=" * 100
        )

        print(
            "05 FAILED SAFELY"
        )

        print(
            "=" * 100
        )

        print(
            f"\n{type(exc).__name__}: {exc}"
        )

        print(
            "\nNo synthetic data were generated and no historical "
            "project artifact was modified."
        )

        print(
            "\nFull traceback:\n"
        )

        traceback.print_exc()

        sys.exit(1)